def create_charts():
    fig1 = visualization_pipeline(
        df=supply_df,
            title='rlusd_fig1',
            # start_date='2024-01-01',
            # end_date='2024-12-31',
            # end_date='2024-10-01',
            chart_type='pie',
            dimensions=dict(height=351, width=730),
            groupby = 'Blockchain',
            num_col='Supply',
            # cols_to_plot='All',
            # line_col=['cumulative_freq'],
            # bar_col=['freg'],
            tickangle=0,
            dropna=True,
            area=True,
            # colors=combined_colors,
            # axes_data=dict(y1=['UAW'],y2=[]),
            tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
            legend_font_size=12,
            # font_family=font_family,
            cumulative_sort=True,
            normalize=False,
            decimals=True,
            decimal_places=0,
            y2=True,
            # min_tick_spacing=50,
            # buffer=3,
            barmode='group',
            mode='lines+markers',
            # font_size=14,
            # line_width=3,
            margin=dict(l=0, r=0, t=50, b=0),
            marker_size=3,
            tickprefix=dict(y1='$',y2=None),
            ticksuffix=dict(y1=None,y2=None),
            axes_titles=dict(y1=None,y2=None),
            show_legend=False,
            hole_size=0,
            line_width=0,
            descending=False,
            buffer = 0.25,
            annotations=True,
            text=True,
            orientation='h',
            sort_list=True,
            autosize=False,
            max_annotation=True,
            annotation_prefix=None,
            auto_title=False,
            axes_font_colors='auto',
            to_reverse=False,
            line_color='black',
            use_single_color=False,
            custom_annotation = ['2022-10-31'],
            # axes_font_colors='auto',
        )
    chartBuilder(
        fig=fig1,
        add_the_date=False,
        clean_columns=True,
        date_xy=dict(x=0.05,y=1.02),
        keep_top_n=False,
        # groupby=True,
        other=True,
        save=False,
        show=False,
        topn=4,
        title_xy=dict(x=0.1,y=0.92),
        title='RLUSD Supply by Chain',
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )

    fig3 = visualization_pipeline(
    df=supply_comp_df,
        title='rlusd_fig3',
        # start_date='2024-01-01',
        # end_date='2024-12-31',
        # end_date='2024-10-01',
        chart_type='pie',
        dimensions=dict(height=351, width=730),
        groupby = 'Status',
        num_col='Amount',
        # cols_to_plot='All',
        # line_col=['cumulative_freq'],
        # bar_col=['freg'],
        tickangle=0,
        dropna=True,
        area=True,
        # axes_data=dict(y1=['UAW'],y2=[]),
        tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
        legend_font_size=12,
        cumulative_sort=True,
        normalize=False,
        decimals=True,
        decimal_places=0,
        y2=True,
        # min_tick_spacing=50,
        # buffer=3,
        barmode='group',
        mode='lines+markers',
        # font_size=14,
        # line_width=3,
        marker_size=3,
        tickprefix=dict(y1='$',y2=None),
        ticksuffix=dict(y1=None,y2=None),
        axes_titles=dict(y1=None,y2=None),
        show_legend=False,
        hole_size=0,
        line_width=0,
        descending=False,
        buffer = 0.25,
        annotations=True,
        text=True,
        orientation='h',
        sort_list=True,
        margin=dict(l=0, r=0, t=100, b=0),
        autosize=False,
        max_annotation=True,
        annotation_prefix=None,
        auto_title=False,
        axes_font_colors='auto',
        to_reverse=False,
        line_color='black',
        use_single_color=False,
        custom_annotation = ['2022-10-31'],
        # axes_font_colors='auto',
    )

    chartBuilder(
        fig=fig3,
        add_the_date=False,
        clean_columns=True,
        date_xy=dict(x=0.05,y=1.02),
        keep_top_n=False,
        # groupby=True,
        other=True,
        save=False,
        show=False,
        title_xy=dict(x=0.1,y=0.9),
        topn=4,
        title='Share of RLUSD Locked in Liquidity Pools'
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )

    fig4 = visualization_pipeline(
    df=combined_rlusd_lp[combined_rlusd_lp.index >= rlusd_xrp_df.index.min()],
        title='rlusd_fig4',
        start_date=str(rlusd_xrp_df.index.min()),
        # end_date='2024-12-31',
        # end_date='2024-10-01',
        chart_type='line',
        dimensions=dict(height=351, width=730),
        groupby = 'blockchain',
        num_col='current_bal',
        # cols_to_plot=["RLUSD_ETH_LP","RLUSD_XRP_LP"],
        # line_col=['cumulative_freq'],
        # bar_col=['freg'],
        tickangle=0,
        dropna=True,
        area=True,
        # axes_data=dict(y1=['total_tvl'],y2=[]),
        # tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
        legend_font_size=12,
        cumulative_sort=True,
        normalize=False,
        decimals=True,
        decimal_places=1,
        y2=True,
        # min_tick_spacing=50,
        # buffer=3,
        barmode='group',
        mode='lines',
        # font_size=14,
        # line_width=3,
        marker_size=3,
        tickprefix=dict(y1='$',y2=None),
        ticksuffix=dict(y1=None,y2=None),
        axes_titles=dict(y1=None,y2=None),
        show_legend=True,
        hole_size=0,
        # line_width=1,
        descending=False,
        margin=dict(l=0, r=0, t=100, b=0),
        legend_background=dict(bgcolor='white',bordercolor='black',
                                                                                                        borderwidth=1, itemsizing='constant',
                                                                                                        yanchor="top",xanchor="center",buffer=8),
        # buffer = 0.25,
        annotations=False,
        legend_placement=dict(x=0.75,y=0.9),
        text=True,
        orientation='h',
        sort_list=True,
        autosize=False,
        max_annotation=False,
        annotation_prefix="$",
        auto_title=False,
        axes_font_colors='auto',
        to_reverse=False,
        line_color='black',
        use_single_color=False,
        custom_annotation = ['2022-10-31'],
        # axes_font_colors='auto',
    )

    chartBuilder(
        fig=fig4,
        add_the_date=True,
        clean_columns=False,
        # date_xy=dict(x=0.05,y=1.02),
        keep_top_n=False,
        # groupby=True,
        other=True,
        title='RLUSD Locked in Liquidity Pools <br>by Chain Over Time',
        title_xy=dict(x=0.1,y=0.9),
        save=False,
        show=False,
        date_xy=dict(x=0.93,y=1.05),
        # title_xy=dict(x=0.1,y=0.9),
        topn=4,
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )

    fig7 = visualization_pipeline(
    df=vol_by_chain,
        title='rlusd_fig7',
        # start_date='2024-01-01',
        # end_date='2024-12-31',
        # end_date='2024-10-01',
        chart_type='pie',
        dimensions=dict(height=351, width=730),
        groupby = 'blockchain',
        num_col='volume',
        # cols_to_plot='All',
        # line_col=['cumulative_freq'],
        # bar_col=['freg'],
        tickangle=0,
        dropna=True,
        area=True,
        # axes_data=dict(y1=['UAW'],y2=[]),
        tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
        legend_font_size=12,
        cumulative_sort=True,
        normalize=False,
        decimals=True,
        decimal_places=0,
        y2=True,
        # min_tick_spacing=50,
        # buffer=3,
        barmode='group',
        mode='lines+markers',
        # font_size=14,
        # line_width=3,
        marker_size=3,
        tickprefix=dict(y1='$',y2=None),
        ticksuffix=dict(y1=None,y2=None),
        axes_titles=dict(y1=None,y2=None),
        show_legend=False,
        hole_size=0,
        line_width=0,
        descending=False,
        buffer = 0.25,
        margin=dict(l=0, r=0, t=100, b=0),
        annotations=True,
        text=True,
        orientation='h',
        sort_list=True,
        autosize=False,
        max_annotation=True,
        annotation_prefix='$',
        auto_title=False,
        axes_font_colors='auto',
        to_reverse=False,
        line_color='black',
        use_single_color=False,
        custom_annotation = ['2022-10-31'],
        # axes_font_colors='auto',
    )
    chartBuilder(
        fig=fig7,
        add_the_date=False,
        clean_columns=False,
        date_xy=dict(x=0.05,y=1.02),
        keep_top_n=False,
        # groupby=True,
        other=True,
        save=False,
        show=False,
        title_xy=dict(x=0.1,y=0.92),
        title='RLUSD Cumulative DEX Volume <br>by Chain',
        topn=4,
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )

    print(f'formatted_today_utc: {formatted_today_utc}')
    print(f'combined_vol.index: {combined_vol.index}')
    # combined_vol[combined_vol.index < formatted_today_utc]

    fig6 = visualization_pipeline(
    df=combined_vol[combined_vol.index < combined_vol.index.max()],
        title='rlusd_fig6',
        start_date=str(rlusd_xrp_df.index.min()),
        # end_date='2024-12-31',
        # end_date='2024-10-01',
        chart_type='bar',
        dimensions=dict(height=351, width=730),
        groupby = 'blockchain',
        num_col='volume',
        # cols_to_plot=["RLUSD_ETH_LP","RLUSD_XRP_LP"],
        # line_col=['cumulative_freq'],
        # bar_col=['freg'],
        tickangle=0,
        dropna=True,
        area=True,
        # colors=combined_colors,
        # axes_data=dict(y1=['total_tvl'],y2=[]),
        # tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
        legend_font_size=12,
        # font_family=font_family,
        legend_placement=dict(x=0.8,y=0.9),
        cumulative_sort=True,
        normalize=False,
        decimals=True,
        decimal_places=1,
        y2=True,
        min_tick_spacing=50,
        # buffer=3,
        # barmode='group',
        mode='lines',
        # font_size=14,
        # line_width=3,
        marker_size=3,
        margin=dict(l=0, r=0, t=50, b=0),
        tickprefix=dict(y1='$',y2=None),
        ticksuffix=dict(y1=None,y2=None),
        axes_titles=dict(y1=None,y2=None),
        show_legend=True,
        hole_size=0,
        # line_width=1,
        descending=True,
        buffer = 3,
        annotations=False,
        text=False,
        orientation='h',
        sort_list=True,
        autosize=False,
        max_annotation=False,
        annotation_prefix="$",
        auto_title=False,
        axes_font_colors='auto',
        to_reverse=False,
        line_color='black',
        use_single_color=False,
        custom_annotation = ['2022-10-31'],
        # axes_font_colors='auto',
    )

    chartBuilder(
        fig=fig6,
        add_the_date=True,
        clean_columns=False,
        date_xy=dict(x=0.87,y=.98),
        title_xy=dict(x=0.1,y=0.9),
        keep_top_n=False,
        # groupby=True,
        other=True,
        title='RLUSD DEX Volume By Chain',
        save=False,
        show=False,
        topn=4,
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )
    fig8 = visualization_pipeline(
    df=combined_vol[combined_vol.index < combined_vol.index.max()],
        title='rlusd_fig8',
        start_date=str(rlusd_xrp_df.index.min()),
        # end_date='2024-12-31',
        # end_date='2024-10-01',
        chart_type='bar',
        dimensions=dict(height=351, width=730),
        groupby = 'blockchain',
        num_col='volume',
        # cols_to_plot=["RLUSD_ETH_LP","RLUSD_XRP_LP"],
        # line_col=['cumulative_freq'],
        # bar_col=['freg'],
        tickangle=0,
        dropna=True,
        area=True,
        # colors=combined_colors,
        # axes_data=dict(y1=['total_tvl'],y2=[]),
        # tickformat=dict(x='%b<br>`%y',y1=None,y2=None),
        legend_font_size=12,
        # font_family=font_family,
        legend_placement=dict(x=0.8,y=0.9),
        cumulative_sort=True,
        normalize=False,
        decimals=True,
        decimal_places=1,
        y2=True,
        min_tick_spacing=50,
        # buffer=3,
        # barmode='group',
        mode='lines',
        # font_size=14,
        # line_width=3,
        marker_size=3,
        margin=dict(l=0, r=0, t=50, b=0),
        tickprefix=dict(y1='$',y2=None),
        ticksuffix=dict(y1=None,y2=None),
        axes_titles=dict(y1=None,y2=None),
        show_legend=True,
        hole_size=0,
        # line_width=1,
        descending=True,
        buffer = 3,
        annotations=False,
        text=False,
        orientation='h',
        sort_list=True,
        autosize=False,
        max_annotation=False,
        annotation_prefix="$",
        auto_title=False,
        axes_font_colors='auto',
        to_reverse=False,
        line_color='black',
        use_single_color=False,
        custom_annotation = ['2022-10-31'],
        # axes_font_colors='auto',
    )

    chartBuilder(
        fig=fig8,
        add_the_date=True,
        clean_columns=False,
        date_xy=dict(x=0.87,y=.98),
        title_xy=dict(x=0.1,y=0.9),
        keep_top_n=False,
        # groupby=True,
        other=True,
        title='RLUSD DEX Volume By Chain',
        save=False,
        show=False,
        topn=4,
        # dashed_line=True,
        # date='2023-04-12',
        # annotation_text='Staked ETH <br> Withdrawl Activated'
    )

    return fig1, fig3, fig4, fig6, fig7 